spring.application.name=internship-management-system

# spring.datasource.url=jdbc:postgresql://localhost:5432/internships
# spring.datasource.username=postgres
# spring.datasource.password=admin

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.thymeleaf.cache=false

server.port=8080